# Generated by Django 5.2.17 on 2026-09-04 08:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokerHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Текущий банк', max_digits=10)),
                ('current_street', models.CharField(choices=[('PREFLOP', 'Preflop'), ('FLOP', 'Flop'), ('TURN', 'Turn'), ('RIVER', 'River'), ('SHOWDOWN', 'Showdown')], default='PREFLOP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position', models.CharField(choices=[('BTN', 'Button'), ('SB', 'Small Blind'), ('BB', 'Big Blind'), ('UTG', 'Under the Gun'), ('MP', 'Middle Position'), ('CO', 'Cutoff')], max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='web.pokerhand')),
            ],
        ),
        migrations.CreateModel(
            name='HandAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(choices=[('PREFLOP', 'Preflop'), ('FLOP', 'Flop'), ('TURN', 'Turn'), ('RIVER', 'River'), ('SHOWDOWN', 'Showdown')], max_length=10)),
                ('action_type', models.CharField(choices=[('FOLD', 'Fold'), ('CHECK', 'Check'), ('CALL', 'Call'), ('BET', 'Bet'), ('RAISE', 'Raise')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='web.handplayer')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='web.pokerhand')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('T', 'T'), ('J', 'J'), ('Q', 'Q'), ('K', 'K'), ('A', 'A')], max_length=1)),
                ('suit', models.CharField(choices=[('s', 'Spades'), ('h', 'Hearts'), ('d', 'Diamonds'), ('c', 'Clubs')], max_length=1)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_cards', to='web.handplayer')),
                ('hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_cards', to='web.pokerhand')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('result_file', models.FileField(blank=True, help_text='Путь к большому JSON/бинарному файлу дерева решений', null=True, upload_to='strategies/')),
                ('summary_metrics', models.JSONField(blank=True, default=dict, help_text='Легковесные агрегированные метрики для отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='web.pokerhand')),
            ],
        ),
    ]
