# Generated by Django 5.2.17 on 2026-08-25 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("params", models.JSONField(default=dict, verbose_name="Параметры")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("queued", "В очереди"),
                            ("running", "Считается"),
                            ("done", "Готово"),
                            ("failed", "Ошибка"),
                        ],
                        default="created",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="Результат"),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="results/",
                        verbose_name="Файл результата",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "core_version",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Версия ядра"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "задача",
                "verbose_name_plural": "задачи",
                "ordering": ["-created_at"],
            },
        ),
    ]
