# Generated by Django 5.2.17 on 2026-09-03 11:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('fold_threshold', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('call_threshold', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('raise_threshold', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PokerHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PREFLOP', 'Preflop'), ('FLOP', 'Flop'), ('TURN', 'Turn'), ('RIVER', 'River'), ('FINISHED', 'Finished')], default='PREFLOP', max_length=10)),
                ('players_count', models.PositiveSmallIntegerField()),
                ('pot_size', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('call_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_hands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_number', models.PositiveSmallIntegerField()),
                ('is_hero', models.BooleanField(default=False)),
                ('stack', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FOLDED', 'Folded'), ('ALL_IN', 'All-in'), ('WINNER', 'Winner'), ('LOSER', 'Loser')], default='ACTIVE', max_length=10)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='web.pokerhand')),
            ],
            options={
                'ordering': ['player_number'],
            },
        ),
        migrations.CreateModel(
            name='HandAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('FOLD', 'Fold'), ('CHECK', 'Check'), ('CALL', 'Call'), ('BET', 'Bet'), ('RAISE', 'Raise'), ('ALL_IN', 'All-in')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('street', models.CharField(choices=[('PREFLOP', 'Preflop'), ('FLOP', 'Flop'), ('TURN', 'Turn'), ('RIVER', 'River')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='web.handplayer')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='web.pokerhand')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=2)),
                ('location', models.CharField(choices=[('HOLE', 'Hole'), ('FLOP', 'Flop'), ('TURN', 'Turn'), ('RIVER', 'River')], max_length=6)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='web.handplayer')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='web.pokerhand')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_count', models.PositiveIntegerField(default=10000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='web.pokerhand')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_requests', to='web.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('FOLD', 'Fold'), ('CALL', 'Call'), ('RAISE', 'Raise')], max_length=5)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('win_probability', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('tie_probability', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('loss_probability', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='web.simulationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iterations', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField(default=0)),
                ('ties', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('win_probability', models.DecimalField(decimal_places=6, max_digits=8)),
                ('tie_probability', models.DecimalField(decimal_places=6, max_digits=8)),
                ('loss_probability', models.DecimalField(decimal_places=6, max_digits=8)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='web.simulationrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddConstraint(
            model_name='handplayer',
            constraint=models.UniqueConstraint(fields=('hand', 'player_number'), name='unique_player_number_per_hand'),
        ),
        migrations.AddConstraint(
            model_name='handplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_hero', True)), fields=('hand',), name='one_hero_per_hand'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('hand', 'card_code'), name='unique_card_per_hand'),
        ),
    ]
