# Generated by Django 5.2.17 on 2026-10-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_task_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="handaction",
            name="hand",
        ),
        migrations.RemoveField(
            model_name="handaction",
            name="player",
        ),
        migrations.RemoveField(
            model_name="handplayer",
            name="hand",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="hand",
        ),
        migrations.DeleteModel(
            name="Card",
        ),
        migrations.DeleteModel(
            name="HandAction",
        ),
        migrations.DeleteModel(
            name="HandPlayer",
        ),
        migrations.DeleteModel(
            name="PokerHand",
        ),
        migrations.DeleteModel(
            name="Strategy",
        ),
    ]
